### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by MaksDragon** [MikuAuahDark/cs2djit#2]
./cs2djit.sh: line 3: 69206 Segmentation fault      (core dumped) LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DIR LD_PRELOAD=$DIR/libcs2djit.so $DIR/cs2d_dedicated $@
how i can fix that?

**Comment by MikuAuahDark** [comment]
What distro are you using? I vaguely remember CS2D in general doesn't work in ArchLinux. Try compiling from source then use `gdb` command with [`LD_PRELOAD` set](https://stackoverflow.com/a/10448351) to the `libcs2djit.so` and send me the output of the `bt` command in GDB when it crashes.

**Comment by MaksDragon** [comment]
ye, i use arch...

**Comment by MaksDragon** [comment]
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
"/home/yomissayy/.steam/steamcmd/cs2d_arena/./cs2djit.sh": not in executable format: file format not recognized
(gdb)

**Comment by MaksDragon** [comment]
My servers running on arch linux. No way to host cs2d server with luajit with arch?

**Comment by MikuAuahDark** [comment]
One option would be bootstrapping [i386 Debian distro](https://wiki.debian.org/Debootstrap) in your ArchLinux. You need to install [`debian-archive-keyring`](https://archlinux.org/packages/community/any/debian-archive-keyring/), [`debootstrap`](https://archlinux.org/packages/community/any/debootstrap/), and [`arch-install-scripts`](https://archlinux.org/packages/extra/any/arch-install-scripts/) for `arch-chroot` command.

Since this is distro-specific issue, I'm unable to fix this.

**Comment by MaksDragon** [comment]
ERROR: ld.so: object './libcs2djit.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
this is on ubuntu my friend

**Comment by MikuAuahDark** [comment]
If that shows when running the dedicated server, then the script uses `os.execute` somewhere, but it's harmless. If you really want to remove the message, use the "`LD_PRELOAD` unset" script in unrealsoftware.
